from typing import Protocol
from server import schemas


class TourRepository(Protocol):
    """Интерфейс шаблона Repository для работы с турами."""

    def add(self, tour: schemas.TourCreate): ...
    def get(self, tour_id: int): ...
    def update(self, tour_id: int, tour: schemas.TourCreate): ...
    def delete(self, tour_id: int) -> bool: ...
    def search(self, name: str | None = None, tour_type: str | None = None, max_price: float | None = None): ...
